### PR TITLE
Update PlayerHandler.cpp

### PR DESCRIPTION
**Pull request by ste-giordano95**
-Add Packet SetPriceAMMO

### CODE REVIEW

**Comment by MuffinMario** [comment]
EDIT wow am I blind. May I ask what changing the last setting variable does?

**Comment by ste-giordano95** [comment]
> 
> 
> EDIT wow am I blind. May I ask what changing the last setting variable does?

on Setting enable "Show "Buy now" menu for ammo on the space map"

**Comment by ste-giordano95** [comment]
you have discord?

**Comment by MuffinMario** [comment]
Yes I do. MuffinMario#1403 :)

**Pull request merged**
